[package]
name = "rust-htslib"
version = "0.24.1-alpha.0"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
description = "This library provides HTSlib bindings and a high level Rust API for reading and writing BAM files."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/rust-bio/rust-htslib.git"
documentation = "https://docs.rs/rust-htslib"
edition = "2018"


[dependencies]
libc = "0.2"
libz-sys = "1.0"
bzip2-sys = { version = "0.1.7", optional = true }
lzma-sys = { version = "0.1.10", optional = true }
itertools = "0.8"
quick-error = "1.2"
newtype_derive = "0.1"
custom_derive = "0.1"
url = "2.1.0"
ieee754 = "0.2"
lazy_static = "1.4.0"
bitflags = "1.1.0"
regex = "1.2.1"
linear-map = "1.2.0"
serde = { version = "^1", optional = true }
bio-types = ">=0.5.1"

[features]
default = ["bzip2", "lzma"]
bzip2 = ["bzip2-sys"]
lzma = ["lzma-sys"]

[dev-dependencies]
tempdir = "0.3"
bincode = "1.1.4"
serde_json = "1.0"
pretty_assertions = "0.6.1"

[build-dependencies]
fs-utils = "1.1.1"
bindgen = {version = "0.51.0", default-features = false}
cc = "1.0"
