[build.env]
passthrough = [
    "RUST_DEBUG",
    "RUST_BACKTRACE",
    "CFLAGS"
]


[target.x86_64-unknown-linux-musl]
image = "brainstorm/cross-x86_64-unknown-linux-musl:1.0.2"
[target.x86_64-unknown-linux-gnu]
image = "brainstorm/cross-x86_64-unknown-linux-gnu:1.0.0"
